language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
# command to install dependencies
install:
  - pip install .
# command to run tests
script: python setup.py test
# only notify when status changes from success to failure
notifications:
  email:
    recipients:
      - code@ramiro.org
    on_failure: change