# General settings that will be available in templates.
site:
    base_url: https://ramiro.org/logya/docs
    author: Ramiro Gómez
    name: Logya documentation


# Settings that affect collections in the document index. Top-level keys of
# collections can be used as document attributes for grouping it in the
# corresponding collection.
collections:
    tags:
        path: tags
        template: index.html


extensions:
    markdown: ['attr_list', 'def_list', 'fenced_code', 'toc']